// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS-XzZl2dnuvuTP9FqrsA70KPKiBgwnGc',
    appId: '1:295274875320:web:f376fb45049d681cf6674d',
    messagingSenderId: '295274875320',
    projectId: 'canvasthoughtsteam',
    authDomain: 'canvasthoughtsteam.firebaseapp.com',
    storageBucket: 'canvasthoughtsteam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVmN8WjfbxIaN29ZjzkkSMOKHw1KKlVk',
    appId: '1:295274875320:android:550ab9d9b2ee4484f6674d',
    messagingSenderId: '295274875320',
    projectId: 'canvasthoughtsteam',
    storageBucket: 'canvasthoughtsteam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT04iDkQZufj5r0XCoshh74ZpMB4PjZRg',
    appId: '1:295274875320:ios:917d80cda6c8d3bcf6674d',
    messagingSenderId: '295274875320',
    projectId: 'canvasthoughtsteam',
    storageBucket: 'canvasthoughtsteam.appspot.com',
    iosBundleId: 'com.team.canvasthoughtsflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT04iDkQZufj5r0XCoshh74ZpMB4PjZRg',
    appId: '1:295274875320:ios:f329107fe0aadbb6f6674d',
    messagingSenderId: '295274875320',
    projectId: 'canvasthoughtsteam',
    storageBucket: 'canvasthoughtsteam.appspot.com',
    iosBundleId: 'com.team.canvasthoughtsflutter.RunnerTests',
  );
}
